/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppCreditsRouteImport } from './routes/app.credits'
import { Route as AppExamplesRouteImport } from './routes/app.examples'
import { Route as AppKeysRouteImport } from './routes/app.keys'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignOutRouteImport } from './routes/auth.sign-out'
import { Route as AppAgentsClientRouteImport } from './routes/app.agents.$client'
import { Route as AppExamplesExampleRouteImport } from './routes/app.examples.$example'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppExamplesRoute = AppExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsClientRoute = AppAgentsClientRouteImport.update({
  id: '/$client',
  path: '/$client',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppExamplesExampleRoute = AppExamplesExampleRouteImport.update({
  id: '/$example',
  path: '/$example',
  getParentRoute: () => AppExamplesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/connections': typeof AppConnectionsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/examples': typeof AppExamplesRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/plans': typeof AppPlansRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$client': typeof AppAgentsClientRoute
  '/app/examples/$example': typeof AppExamplesExampleRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/connections': typeof AppConnectionsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/examples': typeof AppExamplesRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/plans': typeof AppPlansRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$client': typeof AppAgentsClientRoute
  '/app/examples/$example': typeof AppExamplesExampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/connections': typeof AppConnectionsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/examples': typeof AppExamplesRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/plans': typeof AppPlansRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/usage': typeof AppUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$client': typeof AppAgentsClientRoute
  '/app/examples/$example': typeof AppExamplesExampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/connections'
    | '/app/credits'
    | '/app/examples'
    | '/app/keys'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/plans'
    | '/app/settings'
    | '/app/team'
    | '/app/usage'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app/'
    | '/app/agents/$client'
    | '/app/examples/$example'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/connections'
    | '/app/credits'
    | '/app/examples'
    | '/app/keys'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/plans'
    | '/app/settings'
    | '/app/team'
    | '/app/usage'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app'
    | '/app/agents/$client'
    | '/app/examples/$example'
  id:
    | '__root__'
    | '/app'
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/connections'
    | '/app/credits'
    | '/app/examples'
    | '/app/keys'
    | '/app/onboarding'
    | '/app/organization'
    | '/app/plans'
    | '/app/settings'
    | '/app/team'
    | '/app/usage'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app/'
    | '/app/agents/$client'
    | '/app/examples/$example'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credits': {
      id: '/app/credits'
      path: '/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/examples': {
      id: '/app/examples'
      path: '/examples'
      fullPath: '/app/examples'
      preLoaderRoute: typeof AppExamplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agents/$client': {
      id: '/app/agents/$client'
      path: '/$client'
      fullPath: '/app/agents/$client'
      preLoaderRoute: typeof AppAgentsClientRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/app/examples/$example': {
      id: '/app/examples/$example'
      path: '/$example'
      fullPath: '/app/examples/$example'
      preLoaderRoute: typeof AppExamplesExampleRouteImport
      parentRoute: typeof AppExamplesRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsClientRoute: typeof AppAgentsClientRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsClientRoute: AppAgentsClientRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppExamplesRouteChildren {
  AppExamplesExampleRoute: typeof AppExamplesExampleRoute
}

const AppExamplesRouteChildren: AppExamplesRouteChildren = {
  AppExamplesExampleRoute: AppExamplesExampleRoute,
}

const AppExamplesRouteWithChildren = AppExamplesRoute._addFileChildren(
  AppExamplesRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppExamplesRoute: typeof AppExamplesRouteWithChildren
  AppKeysRoute: typeof AppKeysRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppConnectionsRoute: AppConnectionsRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppExamplesRoute: AppExamplesRouteWithChildren,
  AppKeysRoute: AppKeysRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppPlansRoute: AppPlansRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
